services:
  db:
    image: postgres
    container_name: myDatabaseContainer
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: myAppContainer
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
    ports:
      - "8080:8080"

    # ==========코드수정 시 즉시반영 위한 볼륨=========
#    volumes:
#      - ./src:/app/src
#      - ./build.gradle:/app/build.gradle
#      - ./settings.gradle:/app/settings.gradle
#      - ./gradle:/app/gradle
#    command: ./gradlew bootRun # jar 대신 bootRun: 실시간 반영
