services:
  db:
    image: postgres
    container_name: myDatabaseContainer
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    # 데이터 저장 시
  #    volumes:
  #      - ./postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: myAppContainer
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    # messages.properties 적용 위해 추가
    environment:
      - JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8
    env_file:
      - .env